### ISSUE TITLE
Add support for extracting protobins

### ISSUE THREAD

**Issue by jleclanche** [HearthSim/proto-extractor#6]
cf https://github.com/HearthSim/d3

**Comment by Bert-Proesmans** [comment]
I'm not sure what to do with that repository, i need to gather more information on protobins first.

**Comment by jleclanche** [comment]
@Bert-Proesmans don't worry about this, it's pretty unimportant.

**Comment by Bert-Proesmans** [comment]
The script `/protobin_to_proto.py` has been updated to properly extract embedded ProtoFileDescriptors from binaries. This works for protoc as compilation service (AND when compilation mode isn't set to minimal).
C/C++ compiled code is supported through direct extraction of the wire encoded descriptors.
Go compiled code is supported through extraction of GZipped blobs, which contain wire encoded descriptors.
Compilations to other languages might be supported as well, but are untested.
